import React from "react";
import { CalendarOutlined, FireOutlined, FolderOutlined } from "@ant-design/icons";
import { Breadcrumb, Col, Row, Affix } from "antd";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import styles from "../styles/details.module.scss";
import Author from "../components/Author";
import Advert from "../components/Advert";
import axios from "axios";
import marked from 'marked';
import hljs from "highlight.js";
import Footer from "../components/Footer";
import "highlight.js/styles/monokai-sublime.css";
import MarkNav from "../components/MarkNav";
// import hljs from 'highlight.js';
// import 'highlight.js/styles/github.css';

const Details = (props) => {
  const marknav = new MarkNav();
  const renderer = new marked.Renderer();
  renderer.heading = function (text, level, raw) {
    const anchor = marknav.add(text, level);
    return `<a id="${anchor}" href="#${anchor}" class="anchor-fix"><h${level}>${text}</h${level}></a>\n`;
  };

  marked.setOptions({
    renderer: renderer,
    gfm: true,
    pedantic: false,
    sanitize: false,
    tables: true,
    breaks: false,
    smartLists: true,
    smartypants: false,
    highlight: function (code) {
      return hljs.highlightAuto(code).value;
    },
  });

  const html = marked(props.article_content);

  return (
    <div className={styles.details_container}>
      <Head>
        <title>博客详情页</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Row className="comm-main" type="flex" justify="center">
        <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}>
          <div>
            <div className="bread-div">
              <Breadcrumb>
                <Breadcrumb.Item>
                  <Link href="/">
                    <a>首页</a>
                  </Link>
                </Breadcrumb.Item>
                <Breadcrumb.Item>{props.typeName}</Breadcrumb.Item>
                <Breadcrumb.Item>{props.title}</Breadcrumb.Item>
              </Breadcrumb>
            </div>

            <div>
              <div className="details-title">{props.title}</div>
              <div className="list-icon center">
                <span>
                  <CalendarOutlined />
                  {props.addTime}
                </span>
                <span>
                  <FolderOutlined />
                  {props.typeName}
                </span>
                <span>
                  <FireOutlined />
                  {props.view_count}
                </span>
              </div>
              <div
                className="details-content"
                dangerouslySetInnerHTML={{ __html: html }}
              ></div>
            </div>
          </div>
        </Col>
        <Col className="comm-right" xs={0} sm={0} md={7} lg={5} xl={4}>
          <Author />
          <Advert />
          <Affix offsetTop={5}>
            <div className="details-nav comm-box">
              <div className="nav-title">文章目录</div>
              <div className="toc-list">{marknav && marknav.render()}</div>
            </div>
          </Affix>
        </Col>
      </Row>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
};

Details.getInitialProps = async (context) => {
  const id = context.query.id;
  const promise = new Promise((resolve) => {
    axios("http://127.0.0.1:7001/default/getArticleById/" + id).then((res) => {
      resolve(res.data.data[0]);
    });
  });
  return await promise;
};

export default Details;
