import { Button, Col, Row } from "antd";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Author from "../components/Author";
import Advert from "../components/Advert";
import Footer from "../components/Footer";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Row className="comm-main" type="flex" justify="center" gutter={5}>
        <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}>
          左侧
        </Col>
        <Col className="comm-right" xs={0} sm={0} md={8} lg={6} xl={4}>
          <Author />
          <Advert />
        </Col>
      </Row>

      {/* <main className={styles.main}>
        Home
        <Button type="primary">
          hello
        </Button>
      </main>
 */}
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
