import React, { useState, useEffect } from "react";
import { Button, Col, List, Row } from "antd";
import Head from "next/head";
import Header from "../components/Header";
import {
  CalendarOutlined,
  FireOutlined,
  FolderOutlined,
} from "@ant-design/icons";
import styles from "../styles/list.module.scss";
import axios from "axios";
import servicePath from "../config/apiURL";
import Link from "next/link";

const ArticleList = (list) => {
  const [myList, setMyList] = useState(list.data);

  useEffect(() => {
    console.log('llllll');
    setMyList(list.data);
  }, [list]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Row className="comm-main" type="flex" justify="center">
        <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}>
          <div>
            <List
              header={<div>最新日志</div>}
              itemLayout="vertical"
              dataSource={myList}
              renderItem={(item) => (
                <List.Item>
                  <div className="list-title">
                    <Link
                      href={{ pathname: "/details", query: { id: item.id } }}
                    >
                      <a>{item.title}</a>
                    </Link>
                  </div>
                  <div className="list-icon">
                    <span>
                      <CalendarOutlined />
                      {item.addTime}
                    </span>
                    <span>
                      <FolderOutlined />
                      {item.typeName}
                    </span>
                    <span>
                      <FireOutlined />
                      {item.view_count}
                    </span>
                  </div>
                </List.Item>
              )}
            ></List>
          </div>
        </Col>
        <Col className="comm-right" xs={0} sm={0} md={7} lg={5} xl={4}>
          右侧
        </Col>
      </Row>
    </div>
  );
};

ArticleList.getInitialProps = async (context) => {
  const id = context.query.id;
  const promise = new Promise((resolve) => {
    axios(servicePath.getListById + id).then((res) => resolve(res.data));
  });
  return await promise;
};

export default ArticleList;
